run:
  max-same-issues: 0
  max-issues-per-linter: 0
  skip-dirs:
    - wordlists

linters-settings:
  dupl:
    threshold: 200
  errcheck:
    check-type-assertions: false
    check-blank: false
  goconst:
    min-occurrences: 20
  gocyclo:
    min-complexity: 30
  misspell:
    locale: US
  nakedret:
    max-func-lines: 0
  unparam:
    algo: cha
    check-exported: false

linters:
  enable:
    - deadcode
    - dupl
    - errcheck
    - goconst
    - gocyclo
    - gofmt
    - golint
    - goimports
    - gosimple
    - govet
    - ineffassign
    - megacheck
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - structcheck
    - unconvert
    - unparam
    - unused
    - varcheck
