language: go
go:
 - "1.11.x"
 - "1.12.x"
 - "1.13.x"
 - "1.14.x"
 - "release"
 - "tip"

env:
  - GO111MODULE=on

script:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.31.0
  - golangci-lint run

  - go build .
